# https://golangci-lint.run/usage/configuration/#config-file
linters-settings:
  govet:
    disable:
      - composites

linters:
  enable:
    - asciicheck
    - bodyclose
    - goconst
    - goimports
    - unconvert
    - unparam
  disable:
    - errcheck

issues:
  max-same-issues: 0

  exclude-rules:
    - path: tools/cdep/
      linters:
        - goconst