# https://golangci-lint.run/usage/configuration/#config-file

run:
  deadline: 5m
  skip-dirs:
    - genfiles$
    - vendor$
  skip-files:
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"

linters-settings:
  govet:
    check-shadowing: false
    disable:
      - composites

linters:
  enable:
    - asciicheck
    - bodyclose
    - goconst
    - goimports
    - interfacer
    - unconvert
    - unparam
  disable:
    - errcheck

issues:
  exclude:
    - ".*_test.go:\\d+:\\d+: string `.+` has \\d+ occurrences, make it a constant" # exclude goconst issues for tests
    - "should not use dot imports" # exclude for component tests
  max-per-linter: 0
  max-same-issues: 0
